### ISSUE TITLE
Updates to Context Loading

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#193]
Documenting some plans to add additional features to the contextual loading system. This is due to the desire to load partial observations in time as well as in detectors. 

Changes Planned:
* Update the `Context.get_obs()` function to accept a `samples=(start_sample, stop_sample)` argument.
* Add a requirement that Context loaders to accept this argument and also a generic `kwargs` catch all to prevent future updates from breaking them.
* Update ObsFileDb to query for the sample ranges of individual files / frames. 

Once this is complete this will solve #178  and #123 should also be completed as well.

**Comment by mhasself** [comment]
Sounds good!  For the generic kwargs... it should be part of the loader interface that the loader must check that all things in kwargs are None.  I.e. it is ok not to implement something but you should crash rather than ignore something you have been asked for.

The ObsFileDb has a frame_offsets table, as this was always part of the plan ... but it need some fixing.
