### ISSUE TITLE
ValueError arising from load_toast_h5.py

### ISSUE THREAD

**Issue by Ankurdev-astro** [simonsobs/sotodlib#793]
I was running into an error arising from load_toast_h5.py, due to 
`vals, i0, i1 = core.util.get_coindices(dets_in_file, dets)`
https://github.com/simonsobs/sotodlib/blob/0ddec1acdd53caf4018a568183c49483fa567815/sotodlib/io/load_toast_h5.py#L77-L79

I found that this was leading to a ValueError in a case where dets_in_file is same as dets but the order of the elements were different. Here is such an example:

```
Printing from load_toast_h5.py...
 
 dets in args:
['w12_p000_PC_f280_A' 'w12_p000_PC_f280_B' 'w12_p1293_PC_f280_A'
 'w12_p1293_PC_f280_B' 'w12_p1724_PC_f280_A' 'w12_p1724_PC_f280_B'
 'w12_p431_PC_f280_A' 'w12_p431_PC_f280_B' 'w12_p862_PC_f280_A'
 'w12_p862_PC_f280_B']
 
 dets_in_file:
['w12_p000_PC_f280_A', 'w12_p000_PC_f280_B', 'w12_p431_PC_f280_A', 'w12_p431_PC_f280_B', 'w12_p862_PC_f280_A', 'w12_p862_PC_f280_B', 'w12_p1293_PC_f280_A', 'w12_p1293_PC_f280_B', 'w12_p1724_PC_f280_A', 'w12_p1724_PC_f280_B']
```

I fixed the error by modifying to:  `vals, i0, i1 = core.util.get_coindices(sorted(dets_in_file), sorted(dets))`

I suggest that the dets_in_file and dets be sorted before this comparison such that a case where un-ordered but same dets do not throw an error, unless there is a reason the order must match. In my case, sorting both and proceeding worked fine.

Here is a look into the full traceback:

```
Traceback (most recent call last):
..., line 36, in <module>
    tod = ct.get_obs(o)
  File "/vol/arc10/data1/adev/Python-projects/venvs/toast-venv/lib/python3.10/site-packages/sotodlib/core/context.py", line 303, in get_obs
    aman = loader_func(self.obsfiledb, obs_id, dets=dets,
  File "/vol/arc10/data1/adev/Python-projects/venvs/toast-venv/lib/python3.10/site-packages/sotodlib/io/load_toast_h5.py", line 49, in load_toast_h5_obs
    load_toast_h5_file(
  File "/vol/arc10/data1/adev/Python-projects/venvs/toast-venv/lib/python3.10/site-packages/sotodlib/io/load_toast_h5.py", line 79, in load_toast_h5_file
    raise ValueError('dets should be None or [].')
ValueError: dets should be None or [].
```

**Comment by mhasself** [comment]
Thanks for the report ... the check that is failing is `np.any(i1 != i0)`.  That's specifically intended to check whether the requested dets are in the same order as they are on disk.  This is so that we can later do this:
```
                aman.signal[:] = f['detdata']['signal']
```
i.e., copy the data in directly without re-ordering in dimension 0.

It is assumed that when someone asks for `dets=['a', 'b', 'c']`, the implication is that the signal data should be returned with 'a' at index 0, 'b' at index 1, etc.

It is possible to fix this, to support detector subsets / different orderings, by doing a re-ordering copy in such cases.  But I'd rather the user work around this (especially if you're loading all dets already, they're just in an unusual order).

**Comment by Ankurdev-astro** [comment]
Thanks @mhasself for your response. It was solved by taking care of the dets ordering similar to dets in disk. 
I am closing this issue as solved, with a minor suggestion that the docstring/ValueError message may include text reminding the user to request dets in the same order as in disk (which I may have overlooked) if you deem as necessary. Thanks [SOLVED]
